// AUTO-GENERATED by scripts/gen-best-photos.mjs — do not edit by hand.
// 6 best photos per brand folder (>=6 distinct files), deduped by file hash.
export const BEST_PHOTOS = {
  "aqua-game": [
    "/brand/aqua-game/aqua-game-01.jpg",
    "/brand/aqua-game/aqua-game-02.jpg",
    "/brand/aqua-game/aqua-game-03.jpg",
    "/brand/aqua-game/aqua-game-03.png",
    "/brand/aqua-game/aqua-game-04.jpg",
    "/brand/aqua-game/aqua-game-05.jpg"
  ],
  "dgyp": [
    "/brand/dgyp/junior-private-pool-1.jpg",
    "/brand/dgyp/junior-private-pool-2.jpg",
    "/brand/dgyp/junior-private-pool-3.jpg",
    "/brand/dgyp/junior-private-pool-4.jpg",
    "/brand/dgyp/junior-private-pool-5.jpg",
    "/brand/dgyp/junior-private-pool-6.jpg"
  ],
  "malang-skyland": [
    "/brand/malang-skyland/malang-skyland-01.jpg",
    "/brand/malang-skyland/malang-skyland-02.jpg",
    "/brand/malang-skyland/malang-skyland-03.jpg",
    "/brand/malang-skyland/malang-skyland-unnamed-1.gif",
    "/brand/malang-skyland/malang-skyland-05.jpg",
    "/brand/malang-skyland/malang-skyland-08.jpg"
  ],
  "nimo-eye": [
    "/brand/nimo-eye/nimo-eye-01.jpg",
    "/brand/nimo-eye/nimo-eye-02.jpg",
    "/brand/nimo-eye/nimo-eye-02.png",
    "/brand/nimo-eye/nimo-eye-03.jpg",
    "/brand/nimo-eye/nimo-eye-04.jpg",
    "/brand/nimo-eye/nimo-eye-04.png"
  ],
  "nimo-highland": [
    "/brand/nimo-highland/nh-01.jpg",
    "/brand/nimo-highland/nh-02.jpg",
    "/brand/nimo-highland/nh-03.jpg",
    "/brand/nimo-highland/nh-04.jpg",
    "/brand/nimo-highland/nh-05.jpg",
    "/brand/nimo-highland/nh-06.jpg"
  ],
  "nimo-kaldera-toba": [
    "/brand/nimo-kaldera-toba/nimo-kaldera-toba-01.jpg",
    "/brand/nimo-kaldera-toba/nimo-kaldera-toba-02.jpg",
    "/brand/nimo-kaldera-toba/nimo-kaldera-toba-02.png",
    "/brand/nimo-kaldera-toba/nimo-kaldera-toba-03.jpg",
    "/brand/nimo-kaldera-toba/nimo-kaldera-toba-04.jpg",
    "/brand/nimo-kaldera-toba/nimo-kaldera-toba-05.jpg"
  ],
  "nimo-resort-ciater": [
    "/brand/nimo-resort-ciater/nimo-resort-ciater-01.png",
    "/brand/nimo-resort-ciater/nimo-resort-ciater-02.jpg",
    "/brand/nimo-resort-ciater/nimo-resort-ciater-03.png",
    "/brand/nimo-resort-ciater/nimo-resort-ciater-04.png",
    "/brand/nimo-resort-ciater/nimo-resort-ciater-05.png",
    "/brand/nimo-resort-ciater/nimo-resort-ciater-06.png"
  ],
  "nimo-tea-resort": [
    "/brand/nimo-tea-resort/nimo-tea-resort-01.png",
    "/brand/nimo-tea-resort/nimo-tea-resort-02.png",
    "/brand/nimo-tea-resort/nimo-tea-resort-03.png",
    "/brand/nimo-tea-resort/nimo-tea-resort-04.png",
    "/brand/nimo-tea-resort/nimo-tea-resort-05.png",
    "/brand/nimo-tea-resort/nimo-tea-resort-06.jpg"
  ],
  "nimo-water-forest": [
    "/brand/nimo-water-forest/nimo-water-forest-01.jpg",
    "/brand/nimo-water-forest/nimo-water-forest-02.jpg",
    "/brand/nimo-water-forest/nimo-water-forest-03.jpg",
    "/brand/nimo-water-forest/nimo-water-forest-04.jpg",
    "/brand/nimo-water-forest/nimo-water-forest-05.jpg",
    "/brand/nimo-water-forest/nimo-water-forest-06.jpg"
  ],
  "nimo-zoo": [
    "/brand/nimo-zoo/nimo-zoo-01.jpg",
    "/brand/nimo-zoo/nimo-zoo-02.jpg",
    "/brand/nimo-zoo/nimo-zoo-03.jpg",
    "/brand/nimo-zoo/nimo-zoo-04.jpg",
    "/brand/nimo-zoo/nimo-zoo-05.jpg",
    "/brand/nimo-zoo/nimo-zoo-06.jpg"
  ],
  "pinaru-park": [
    "/brand/pinaru-park/pinaru-park-01.png",
    "/brand/pinaru-park/pinaru-park-02.png",
    "/brand/pinaru-park/pinaru-park-03.png",
    "/brand/pinaru-park/pinaru-park-04.jpg",
    "/brand/pinaru-park/pinaru-park-05.jpg",
    "/brand/pinaru-park/pinaru-park-06.jpg"
  ],
  "punceling-park": [
    "/brand/punceling-park/4320b925-e19f-458d-9c87-cd9f0036b6c4.jpg",
    "/brand/punceling-park/punceling-park-01.jpg",
    "/brand/punceling-park/punceling-park-03.jpg",
    "/brand/punceling-park/punceling-park-04.jpg",
    "/brand/punceling-park/punceling-park-05.jpg",
    "/brand/punceling-park/punceling-park-06.jpg"
  ],
  "savia-hotel-resort": [
    "/brand/savia-hotel-resort/savia-hotel-resort-01.png",
    "/brand/savia-hotel-resort/savia-hotel-resort-02.jpg",
    "/brand/savia-hotel-resort/savia-hotel-resort-03.jpg",
    "/brand/savia-hotel-resort/savia-hotel-resort-04.png",
    "/brand/savia-hotel-resort/savia-hotel-resort-05.jpg",
    "/brand/savia-hotel-resort/savia-hotel-resort-06.jpg"
  ]
};
