/* Image inventory + migration seed.

   Every image the site uses comes from data.js (IMG: Google Sites hotlinks,
   FB: Unsplash fallback). Running this WITHOUT flags prints the full inventory
   of unique URLs — the map you asked for in FASE 2.5 "Pindahkan Gambar".

   With --download it downloads the ones it can reach into src/assets/nimo/
   and writes assets/images.mjs so the <NimoImage> component can serve them as
   optimised WebP. Google's lh3 host returns 403 to anonymous tools: those are
   listed so you can grab them from the logged-in Google Sites editor.

   Usage:
     node scripts/images-seed.mjs            # print inventory
     node scripts/images-seed.mjs --download # download + write assets/images.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, extname } from 'node:path';
import { DESTINATIONS, HOTELS, WAHANA, HERO_SLIDES, MOMENTS, GALLERY, IMG, FB } from '../src/lib/data.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ASSETS = join(ROOT, 'src', 'assets', 'nimo');
const DOWNLOAD = process.argv.includes('--download');

// Key -> { url, where } for every unique image in use.
const entries = new Map();
const add = (key, url, where) => {
  if (!url) return;
  if (!entries.has(url)) entries.set(url, { key, url, where: [] });
  entries.get(url).where.push(where);
};

for (const [key, url] of Object.entries(IMG)) add(key, url, 'IMG');
for (const [key, url] of Object.entries(FB)) add('fb-' + key, url, 'FB');

for (const d of DESTINATIONS) {
  add(d.id + '-main', d.img, `destinasi/${d.id}`);
  add(d.id + '-fb', d.fb, `destinasi/${d.id} (fallback)`);
  d.gallery?.forEach((g, i) => add(d.id + `-g${i + 1}`, g, `destinasi/${d.id} galeri`));
}
for (const h of HOTELS) {
  add(h.id + '-main', h.img, `penginapan/${h.id}`);
  h.rooms.forEach(r => add(h.id + '-' + r.id, r.img, `penginapan/${h.id} ${r.name}`));
}
WAHANA.forEach(w => add('wahana-' + w.name.toLowerCase().replace(/\s+/g, '-'), w.img, 'wahana'));
HERO_SLIDES.forEach((s, i) => add('hero-' + (i + 1), s.img, 'hero'));
MOMENTS.forEach((m, i) => add('moment-' + (i + 1), m.img, 'moments'));
GALLERY.forEach((g, i) => add('gallery-' + (i + 1), g.img, 'gallery'));
add('auth-bg', IMG.mist, 'AuthShell');

const list = [...entries.values()].sort((a, b) => a.key.localeCompare(b.key));

console.log(`\n=== INVENTARIS GAMBAR NIMO ===  (${list.length} URL unik)`);
for (const e of list) {
  console.log(`\n[${e.key}]`);
  console.log(`  URL: ${e.url}`);
  console.log(`  Dipakai di: ${e.where.join(', ')}`);

  const name = e.key + (extname(new URL(e.url).pathname) === '.png' ? '.png' : '.jpg');
  console.log(`  File lokal nanti: src/assets/nimo/${name}`);
}

if (!DOWNLOAD) {
  console.log('\n(no download — jalankan dengan --download untuk mengunduh)');
  process.exit(0);
}

console.log('\n=== MENGUNDUH FILES ===');
mkdirSync(ASSETS, { recursive: true });
const ok = [];
const blocked = [];

for (const e of list) {
  const name = e.key + (extname(new URL(e.url).pathname) === '.png' ? '.png' : '.jpg');
  const dest = join(ASSETS, name);
  const isGoogle = e.url.includes('lh3.googleusercontent.com');
  try {
    const res = await fetch(e.url, { headers: { 'User-Agent': 'Mozilla/5.0' } });
    if (!res.ok) throw new Error('HTTP ' + res.status);
    writeFileSync(dest, Buffer.from(await res.arrayBuffer()));
    console.log(`  OK   ${name}  (${(res.headers.get('content-length') || '?')} B)`);
    ok.push({ key: e.key, name });
  } catch (err) {
    const msg = isGoogle
      ? 'DIBLOKIR Google (403) — unduh manual dari editor Google Sites'
      : err.message;
    console.log(`  GAGAL ${name}  — ${msg}`);
    blocked.push({ key: e.key, url: e.url, name });
    e.name = name;
  }
}

// assets/images.mjs so <NimoImage> can resolve by key — keys missing a file
// simply won't be found and the component falls back to the remote img.
const imports = ok
  .sort((a, b) => a.key.localeCompare(b.key))
  .map(({ key, name }) => `  ${JSON.stringify(key)}: () => import('./${name}'),`)
  .join('\n');
writeFileSync(
  join(ROOT, 'src', 'assets', 'nimo', 'images.mjs'),
  `/* Generated by scripts/images-seed.mjs --download. Maps image key -> lazy
   import so <NimoImage> can hand each file to astro:assets (WebP + sizes). */
export const nimoImages = {
${imports}
};

export const hasNimo = key => key in nimoImages;
`,
);

// Instructions for the blocked Google-hosted files.
if (blocked.length) {
  const listFile = join(ROOT, 'ASSETS-UNDUH-MANUAL.txt');
  writeFileSync(
    listFile,
    'File berikut DIBLOKIR Google saat diunduh otomatis (403).\nSalin dari editor Google Sites yang sudah login, simpan di:\n  src/assets/nimo/<nama file>\n\n' +
      blocked.map(b => `${b.name}\n  ${b.url}`).join('\n\n') + '\n',
  );
  console.log(`\n${blocked.length} file Google menunggu unduhan manual → lihat ASSETS-UNDUH-MANUAL.txt`);
}

console.log(`\nSelesai: ${ok.length} terunduh (src/assets/nimo), ${blocked.length} manual.`);